# Generated by Django 3.2.3 on 2023-09-15 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230915_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество не может быть меньше:1.'), django.core.validators.MaxValueValidator(limit_value=9999, message='Количество не может быть больше:9999.')], verbose_name='Количество'),
        ),
    ]
